using System.Windows; using System.Windows.Controls; using DirectorFamilyTravelDesk.Models;
namespace DirectorFamilyTravelDesk.Views;
public partial class DashboardView : UserControl,IRefreshable
{
    private List<TripListItem> _all=new(); private List<TripListItem> _filtered=new();
    public DashboardView(){InitializeComponent();ViewFilter.SelectedIndex=0;}
    public void RefreshData(){_all=App.Repository.GetTrips(); BuildMonths(); ApplyFilters();}
    private void BuildMonths(){var selected=MonthFilter.SelectedValue as string;MonthFilter.Items.Clear();MonthFilter.Items.Add("All Months");foreach(var m in _all.Select(x=>new DateTime(x.DepartureDate.Year,x.DepartureDate.Month,1)).Distinct().OrderBy(x=>x))MonthFilter.Items.Add(m.ToString("MMM-yyyy"));MonthFilter.SelectedItem=selected!=null&&MonthFilter.Items.Contains(selected)?selected:"All Months";}
    private string ViewName()=>((ViewFilter.SelectedItem as ComboBoxItem)?.Content?.ToString())??"Active Trips";
    private void ApplyFilters(){if(ViewFilter.SelectedItem==null||MonthFilter.SelectedItem==null)return;var q=_all.AsEnumerable();var month=MonthFilter.SelectedItem?.ToString();if(month!="All Months"&&DateTime.TryParseExact(month,"MMM-yyyy",null,System.Globalization.DateTimeStyles.None,out var md))q=q.Where(x=>x.DepartureDate.Year==md.Year&&x.DepartureDate.Month==md.Month);var view=ViewName();q=view switch{"Active Trips"=>q.Where(x=>x.Status!="Completed"&&x.Status!="Cancelled"),"Upcoming"=>q.Where(x=>x.DepartureDate>=DateTime.Today&&x.Status!="Completed"&&x.Status!="Cancelled"),"All Trips"=>q,_=>q.Where(x=>x.Status==view)};_filtered=q.OrderBy(x=>x.DepartureDate).ToList();var old=(TripFilter.SelectedItem as TripListItem)?.Id;TripFilter.ItemsSource=null;TripFilter.ItemsSource=_filtered;if(old.HasValue)TripFilter.SelectedItem=_filtered.FirstOrDefault(x=>x.Id==old.Value);if(TripFilter.SelectedItem==null)TripFilter.SelectedIndex=_filtered.Count>0?0:-1;UpdateKpis(month);UpcomingGrid.ItemsSource=_filtered.Where(x=>x.DepartureDate>=DateTime.Today&&x.Status!="Completed"&&x.Status!="Cancelled").Take(3).ToList();ShowTrip(TripFilter.SelectedItem as TripListItem);}
    private void UpdateKpis(string? month){IEnumerable<TripListItem> q=_all;if(month!="All Months"&&DateTime.TryParseExact(month,"MMM-yyyy",null,System.Globalization.DateTimeStyles.None,out var md))q=q.Where(x=>x.DepartureDate.Year==md.Year&&x.DepartureDate.Month==md.Month);KUpcoming.Text=q.Count(x=>x.DepartureDate>=DateTime.Today&&x.Status!="Completed"&&x.Status!="Cancelled").ToString();KAwaiting.Text=q.Count(x=>x.Status=="Awaiting Approval").ToString();KApproved.Text=q.Count(x=>x.Status=="Approved").ToString();KBooked.Text=q.Count(x=>x.Status=="Booked").ToString();KCompleted.Text=q.Count(x=>x.Status=="Completed").ToString();KFiltered.Text=_filtered.Count.ToString();}
    private void ShowTrip(TripListItem? x){if(x==null){RouteText.Text="Select a trip";DateText.Text=TravellerText.Text=PaxText.Text=HotelText.Text=TransportText.Text=OnwardFlightText.Text=ReturnFlightText.Text=OnwardMetaText.Text=ReturnMetaText.Text=StatusText.Text=NextActionText.Text=CostText.Text="";return;}RouteText.Text=x.RouteLabel.Replace(" → ",x.ReturnDate.HasValue?" ⇄ ":" → ");DateText.Text=x.ReturnDate.HasValue?$"{x.DepartureDate:dd MMM yyyy} – {x.ReturnDate:dd MMM yyyy}":$"{x.DepartureDate:dd MMM yyyy}";TravellerText.Text=x.Travellers;PaxText.Text=x.Pax.ToString();HotelText.Text=x.Hotel??"—";TransportText.Text=string.Join(" · ",new[]{x.Transport,x.TransportDetails}.Where(s=>!string.IsNullOrWhiteSpace(s)));OnwardFlightText.Text=x.OnwardFlight??"Not selected";OnwardMetaText.Text=$"PNR: {x.OnwardPnr??"—"}   Seats: {x.OnwardSeats??"—"}";ReturnFlightText.Text=x.ReturnFlight??"Not selected";ReturnMetaText.Text=$"PNR: {x.ReturnPnr??"—"}   Seats: {x.ReturnSeats??"—"}";StatusText.Text=x.Status??"—";NextActionText.Text=x.NextAction??"—";CostText.Text=x.TotalCost.HasValue?$"₹{x.TotalCost:N0}":"—";}
    private void Filter_Changed(object s,SelectionChangedEventArgs e){if(IsLoaded)ApplyFilters();}
    private void TripFilter_SelectionChanged(object s,SelectionChangedEventArgs e)=>ShowTrip(TripFilter.SelectedItem as TripListItem);
    private void NewTrip_Click(object s,RoutedEventArgs e){var w=new TripEditorWindow{Owner=Window.GetWindow(this)};if(w.ShowDialog()==true)RefreshData();}
}